export const LISTING_STATUS_VALUES = ["ACTIVE", "SOLD", "EXPIRED", "PENDING", "REJECTED", "ARCHIVED"] as const;
export const SUBSCRIPTION_STATUS_VALUES = ["ACTIVE", "PAST_DUE", "CANCELED", "INCOMPLETE", "INCOMPLETE_EXPIRED", "TRIALING", "UNPAID"] as const;
export const DEFAULT_PAGE_SIZE = 20;
